### PR TITLE
2020 09 21 - 05

### PR DESCRIPTION
**Pull request by JohannesMerz**

### CODE REVIEW

**Comment by JohannesMerz** [comment]
hello there

**Comment by JohannesMerz** [comment]
hello there

**Comment by JohannesMerz** [comment]
hello there

**Comment by JohannesMerz** [comment]
ah ha!

**Comment by JohannesMerz** [comment]
hoho!

**Comment by sime** [comment]
Content needs to include the whole link:

```
The changes are ready to be reviewed on Bojagi: [https://bojagi.io/app/github/sime/bojagi-demo/pull/5](https://bojagi.io/app/github/sime/bojagi-demo/pull/5)
```

**Pull request merged**
